# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
- master
- hardik/arm_examples_2
- CI_Test

# variables:
#   ubuntu14: 'ubuntu:14.04'
#   ubuntu16: 'ubuntu:16.04'
#   ubuntu18: 'ubuntu:18.04'

pool:
  vmImage: 'Ubuntu-16.04'

# jobs:
# - job: test_linux
  
  # pool:
    # vmImage: 'ubuntu-16.04'
    # name: Hosted Ubuntu 1604
  # container:
    # image: $(ubuntu18)
    # options: --user root

steps:
- bash: |
    mkdir build
    cd build
    echo $PATH
  # cmake ../projects/cmake/
  #   make
  displayName: 'Build Linux x86_64'



  