# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- hardik/arm_examples_2
- CI_Test

pool:
  vmImage: 'ubuntu-16.04'
  name: Hosted Ubuntu 1604

# These steps are the only job being run, in every container.
jobs:
- job: test_linux

  pool: 
    vmImage: 'ubuntu-latest'
    name: Hosted Ubuntu Latest

  strategy:
    matrix:
      ubuntu14:
        containerImage: ubuntu:14.04
      ubuntu16:
        containerImage: ubuntu:16.04
      ubuntu18:
        containerImage: ubuntu:18.04

  container: 
    image: $[variables['containerImage']]
    options: --user root

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
      architecture: 'x64'

  - bash: |
      apt
      sudo apt-get install python-numpy
      mkdir build
      cd build
      cmake ../projects/cmake/
      make
    displayName: 'Testing build on ubuntu'

- job: print_success
  steps:
  - script: printenv


    